spring:
  datasource:
    url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mustache:
    check-template-location: false
server:
  port: 9090

blob-storage:
  container: microtema
service-bus:
  queue-name: microtema.process.definition.queue
  topic-name: microtema.process.definition.topic
  topic-subscription: microtema.subscription
